### ISSUE TITLE
add button for Save and Close

### ISSUE THREAD

**Issue by athurstonbmi** [hashitha/sigrisissues#13]
It is annoying to have to close the tab after saving. Either have the save button close the patient tab, or add a save and close button which closes the patient tab, and goes back to the previous tab that was open.

![image](https://cloud.githubusercontent.com/assets/17734804/13797143/4f64f844-eb46-11e5-8bb5-ac1720de126e.png)

**Comment by hashitha** [comment]
Fixed, Save button will close form now.
