### ISSUE TITLE
New patient window is in front of everything (chrome ect)

### ISSUE THREAD

**Issue by jasonlt86** [hashitha/sigrisissues#2]
New patient window is set on top of all. Can't open chrome and browse for something, then return to the new patient page. chrome will open, however new patient window stays in front.
![image](https://cloud.githubusercontent.com/assets/17632216/13516953/bd35e2da-e1f9-11e5-9902-1ba61d5e578d.png)

**Comment by ChaithikaPrabudda** [comment]
new patient and edit patient window now changed as chrome tab except in the appointment creating window.
