### ISSUE TITLE
save and close on settings not working correctly

### ISSUE THREAD

**Issue by jasonlt86** [hashitha/sigrisissues#22]
![image](https://cloud.githubusercontent.com/assets/17632216/14871919/90af075a-0d19-11e6-96fb-d9603b1f55a7.png)

![image](https://cloud.githubusercontent.com/assets/17632216/14871926/a13f5070-0d19-11e6-9143-207e4a67d37c.png)

![image](https://cloud.githubusercontent.com/assets/17632216/14871938/baf74518-0d19-11e6-8538-858619ea7725.png)

**Comment by ChaithikaPrabudda** [comment]
unable to recreate the issue. please explain more.

**Comment by jasonlt86** [comment]
Upon clicking save and close, it then changes to second screenshot. You have to hit the X to exit. Save and close should close as well. If you hit save and close a second time, it gives the error in the 3rd screenshot.

**Comment by hashitha** [comment]
Renamed to Save from Save & Close
