### ISSUE TITLE
technologist screen - worksheet preview and scan document not showing anything

### ISSUE THREAD

**Issue by jasonlt86** [hashitha/sigrisissues#25]
![image](https://cloud.githubusercontent.com/assets/17632216/14872268/2b4fedd0-0d1d-11e6-96f8-607d49504197.png)

**Comment by ChaithikaPrabudda** [comment]
can you please tell me the testing appointment data in-order to test from development end.

**Comment by jasonlt86** [comment]
Dildo Baggins, ct 28th april

**Comment by ChaithikaPrabudda** [comment]
fixed. new pane added view all scan attachments. please reset the layout before testing.
