### ISSUE TITLE
when adding a cc doctor, can't specify delivery preference 

### ISSUE THREAD

**Issue by jasonlt86** [hashitha/sigrisissues#3]
when adding a cc doctor, can't specify delivery preference 

![image](https://cloud.githubusercontent.com/assets/17632216/13517052/d17ed7be-e1fa-11e5-98ce-36b940f09cbd.png)

**Comment by hashitha** [comment]
Looks like it happens when the height of the window is small. Will need to look at rearranging the layout

**Comment by ChaithikaPrabudda** [comment]
issue is fixed. delivery types will be appear.
