### ISSUE TITLE
new feature request

### ISSUE THREAD

**Issue by jasonlt86** [hashitha/sigrisissues#37]
![image](https://cloud.githubusercontent.com/assets/17632216/15167658/407793c6-175d-11e6-9324-8aa56c1418df.png)

please have option to zoom in and out of worksheets in typing screen. maybe left click and drag to zoom in and out or something like that would be handy.

**Comment by ChaithikaPrabudda** [comment]
this feature added to the patient report form. user can zoom in/out by using crt+mouse wheel. and also have some features if user right clicks on image.
