### ISSUE TITLE
selecting authorise doesn't close the case or go to the next one. nothing happens.

### ISSUE THREAD

**Issue by jasonlt86** [hashitha/sigrisissues#38]
![image](https://cloud.githubusercontent.com/assets/17632216/15167694/977e6fc8-175d-11e6-92b1-04eed1a318d6.png)

**Comment by ChaithikaPrabudda** [comment]
can you please explain the how you open this window. (just tell the steps)

**Comment by ChaithikaPrabudda** [comment]
this is fixed
