### ISSUE TITLE
Cancelled Appointments staying in calendar 

### ISSUE THREAD

**Issue by athurstonbmi** [hashitha/sigrisissues#7]
Created an appointment. Cancelled the appointment and it stayed on the calendar. Unable to book an appointment in this slot. 

![image](https://cloud.githubusercontent.com/assets/17734804/13624065/fb298b6a-e5e5-11e5-9fd5-72c25327a6a4.png)

**Comment by ChaithikaPrabudda** [comment]
remove cancelled appointments from the schedule.
